### ISSUE TITLE
Topic 13 "Storing large files on EOS" does not refer to any file 

### ISSUE THREAD

**Issue by mick-mulder** [lhcb/first-analysis-steps#152]
It refers to 09-eos-storage.html, while in the github it is named 11-eos-storage.html.
What do you want to fix, the link or the filename?

**Comment by betatim** [comment]
Not quite sure I understand what you are referring to. Can you link to the line in the `md` file that refers to the wrong file?

Due to reorganising the order of the lessons several times the numbers in the file names have stopped corresponding to their order. This is indeed quite confusing and should be fixed. Do we anticipate other re-shuffles? If not I'd support a PR that makes the filenames match the actual order.

**Comment by alexpearce** [comment]
I saw this in the lesson. People had the index page open and went to click on the EOS lesson, but PR #149 changed the filename and was merged mid-lesson. This meant the now-outdated link returned a 404.

So, I think we can close this. Thanks for the bug report @mick-mulder, do you think this is OK now?

**Comment by mick-mulder** [comment]
You're welcome Alex, I think we can close this now. Should the consistent numbering of filenames be made into a separate issue?

**Comment by alexpearce** [comment]
Yep. For the record, I would be in favour of just naming the files as the titles of the lessons, omitting the number entirely.

**Comment by betatim** [comment]
Thank you for the reporting, and let's discuss the renaming in #153
