### ISSUE TITLE
migrate lesson 05 to dst-explorer

### ISSUE THREAD

**Issue by pseyfert** [lhcb/first-analysis-steps#158]
the usage of `first.py` can be avoided when using Bender's dst-explorer. imho this also facilitates email communication about exploring dsts, where then custom `first.py` files don't need to be discussed. Furthermore users don't need to stay up to date in their custom `first.py` as they will get the dst-explorer maintenance by the bender developers.

**Comment by apuignav** [comment]
I agree this could be an improvement. This was debated and the usage of
`Bender` was disfavored because the idea was to keep things as pure and as
non-magical as possible. I think we could (should?) have this discussion
again and settle the topic once and for all. At least we could add some
reference to the existance of `Bender`'s `dst-explorer` (well, as far as
Vanya told me this is now renamed to simply `bender`) so, after they've
learned, they can use the premade tool and not have to keep their
`first.py` up-to-date.

On Sat, Nov 28, 2015 at 3:44 PM, pseyfert notifications@github.com wrote:

> the usage of first.py can be avoided when using Bender's dst-explorer.
> imho this also facilitates email communication about exploring dsts, where
> then custom first.py files don't need to be discussed. Furthermore users
> don't need to stay up to date in their custom first.py as they will get
> the dst-explorer maintenance by the bender developers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhcb/first-analysis-steps/issues/158.

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
Some of the discussion is in #81 and unfortunately the rest happened in a chat, not an issue.

The aim of the lesson is not to say "this is how you advance until the stripping decision is `True`", the aim is to show people that there is no magic involved with a DST and what is in it. You can look around with a simple interactive python session and poke things. The reason not to use Bender for this poking around at the lowest level is that Bender does lots of smart things when you start it up. Smart things are useful but only if you never ever have to look under the hood (because they either always work and do what you expect or when they don't work/do what you expect there is excellent documentation to read).

To gain understanding you do have to look under the hood and that is nearly impossible with Bender (it lacks documentation to guide those who know very little python and very little about LHCb software). So I see it more as a power tool you use when you get more confident and bored of maintaining your own little snippets, as a starter though it is always better to learn that something like Bender actually does not do anything particularly difficult/expert.

Maybe we could add a callout saying "there is also bender if you need a power tool" or we have a lesson in `second-analysis-steps`?

**Comment by pseyfert** [comment]
sorry for having missed the duplication #81. let me just add that i consider dst-explorer not a strippingoutput search engine but rather a gaudipython shell where somebody else already did what i'd have to do anyhow, and tool instantiation etc. still work. and consequently haven't used gaudipython since the dst-explorer was released.
anyhow, i see there are good points for keeping the tutorials low level. just placing an advertiser like  apuignav suggested seems appropriate?

**Comment by apuignav** [comment]
I think we should add something in the end, in the lines of: "well, now you
know how it works, do yourself a favor and just use `Bender`". If we agree
I'll add a PR as soon as I have time.

On Sat, Nov 28, 2015 at 6:18 PM, pseyfert notifications@github.com wrote:

> sorry for having missed the duplication #81
> https://github.com/lhcb/first-analysis-steps/pull/81. let me just add
> that i consider dst-explorer not a strippingoutput search engine but rather
> a gaudipython shell where somebody else already did what i'd have to do
> anyhow, and tool instantiation etc. still work. and consequently haven't
> used gaudipython since the dst-explorer was released.
> anyhow, i see there are good points for keeping the tutorials low level.
> just placing an advertiser like apuignav suggested seems appropriate?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhcb/first-analysis-steps/issues/158#issuecomment-160321783
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
Let's see that PR!

**Comment by alexpearce** [comment]
Yeah I think that's the best compromise @apuignav. I learnt _a lot_ having written my own DST explorer script using the lessons; it demystified things. Bender adds another layer of complexity, though it saves time if you already know what you want and understand the underlying concepts.

:+1: for the PR!

**Comment by alexpearce** [comment]
Closed by #160.
