### ISSUE TITLE
Move to v40r2

### ISSUE THREAD

**Issue by henryiii** [lhcb/first-analysis-steps#174]
I'm looking at changing the version to v40r2. I'm running the examples with the new version, and plan to provide a PR once I complete them. Please let me know if there's a reason not to do this. So far it is working fairly well.

**Comment by alexpearce** [comment]
The advice from the DaVinci managers is to use to the latest version when starting an analysis, and to then stick with that version until completion. There are some caveats to this, such as when one wants to re-run certain things like the stripping when one should use the version that was used originally, rather than the latest and greatest, and that one should check the release notes to see if there's something in the latest that isn't compatible with what one wants to do.

Still, as long as the suite of lessons works with v40r2, I have no problem if the lessons were updated to use it (actually I think it would be a Good Thing).
